language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - setup=basic

sudo: false

services:
  - mysql
  - postgresql


before_install:
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'use test;'
  - mysql -e 'source tests/DB/testMysql.sql;'
  - psql -c 'create database test;' -U postgres
  - psql -h localhost -d test -U postgres -f tests/DB/testPgsql.sql

install:
  - travis_retry composer install --no-interaction --prefer-source


script: vendor/bin/phpunit
